### ISSUE TITLE
请问能不能把对应的论文发给我呢谢谢 liang_yingshuo@163.com

### ISSUE THREAD

**Issue by insoliang** [hey2525/Road-boundary-edge-curb-detection#1]

**Comment by wzhnjust** [comment]
请问您有论文原件了吗，方便发一份给我吗1113967466@qq.com谢谢~

**Comment by insoliang** [comment]
不好意思作者没有回复我论文原件，我只在网上找到了一篇类似的，复现了那篇论文




| |
梁迎硕
学生
|
|
学校：南开大学
联系方式：18811650316
邮箱：liang_yingshuo@163.com
地址：天津市海河教育园区同砚路38号南开大学津南校区
|

签名由 网易邮箱大师 定制

在2020年12月28日 09:46，wzh 写道：

请问您有论文原件了吗，方便发一份给我吗1113967466@qq.com谢谢~

**Comment by zhu-bingo** [comment]
请问你复现的效果怎么样，请问您有没有安装autoware

**Comment by insoliang** [comment]
> 请问你复现的效果怎么样，请问您有没有安装autoware

**Comment by insoliang** [comment]
> > 请问你复现的效果怎么样，请问您有没有安装autoware

**Comment by insoliang** [comment]
> 请问你复现的效果怎么样，请问您有没有安装autoware

你可以加我qq交流 1332203855
